#### Numpy

In [1]:
!pip install numpy

In [ ]:
import numpy as np
# Creation of an Array
# 1D Array
arr1=np.array([1,2,3,4,5]) #Can be use list,tuple,dict
print(arr1)
print(type(arr1))
print(arr1.shape) #1D array


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [12]:
arr2=np.array([1,2,3,4,5,6,7,8,9,10])
arr2.reshape(2,5) # 2D Array
# arr2.reshape(x,y) # 2D Array        x---> x rows
#                                     y---> y columns

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
# We can directly reshape it 
# 2D Array
arr3=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr3)
print(arr3.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [18]:
# Inbuilt functions
np.arange(3,10,3)
np.arange(3,10,3).reshape(3,1)
# print(type(np.arange(3,10,3)))
# print(np.arange(x,y,z))    x==> Starting     y==> Ending    z==> Diffrence

array([[3],
       [6],
       [9]])

In [22]:
np.ones((3,4)) #Matrix with 3x4 filled with all 1s


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.zeros((3,4)) #Matrix with 3x4 filled with all 0

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# Atteributes of NumpyArray

print(arr1.dtype)
print(arr1.shape)
print(arr1.ndim)
print(arr1.itemsize)
print(arr1.size)
print(arr1.nbytes) #Total bytes used by the array
print(arr1.T) #Transpose of the array
print(arr1.reshape(5,1)) #Reshape the array to 5 rows and 1 column
print(arr1.reshape(1,5)) #Reshape the array to 1 row and 5 columns
print(arr1.reshape(5,1).shape) #Shape of the reshaped array
print(arr1.reshape(5,1).ndim) #Number of dimensions of the reshaped array
print(arr1.reshape(5,1).itemsize) #Size of each element in the reshaped array
print(arr1.reshape(5,1).size) #Total number of elements in the reshaped array
print(arr1.reshape(5,1).nbytes) #Total bytes used by the reshaped array
print(arr1.reshape(5,1).T) #Transpose of the reshaped array


int64
(5,)
1
8
5
40
[1 2 3 4 5]
[[1]
 [2]
 [3]
 [4]
 [5]]
[[1 2 3 4 5]]
(5, 1)
2
8
5
40
[[1 2 3 4 5]]


In [ ]:
# Vectorisation operations 

In [33]:
arr4=np.array([1,2,3,4,5])
arr5=np.array([6,7,8,9,10])

arr5=arr4+arr5 #Element wise addition
print(arr5)

arr6=arr4-arr5 #Element wise Substraction
print(arr6)

arr7=arr4*arr5 #Element wise Multiplication
print(arr7)

arr8=arr4/arr5 #Element wise Divisiom
print(arr8)

[ 7  9 11 13 15]
[ -6  -7  -8  -9 -10]
[ 7 18 33 52 75]
[0.14285714 0.22222222 0.27272727 0.30769231 0.33333333]


In [34]:
# Universal functions

arr=np.array([1,2,3,4,5])

print(np.sqrt(arr))
print(np.exp(arr))
print(np.log(arr))
print(np.sin(arr))
print(np.cos(arr))
print(np.tan(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501]


In [41]:
# Array Sliceing and indexing

arr9=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
print(arr9)
print(arr9[1,1])
print(arr9[1,2])
print(arr9[1,3])
print(arr9[1:,4:])
print(arr9[2,4])
print(arr9[0:2,0:3])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
7
8
9
[[10]
 [15]
 [20]]
15
[[1 2 3]
 [6 7 8]]


In [42]:
# Modify array elements
arr9[0,0]=100
print(arr9)

[[100   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19  20]]


In [43]:
# Normalization of array
arr10=np.array([[1,2,3],[4,5,6],[7,8,9]])
mean=np.mean(arr10)
print(mean)
std=np.std(arr10)
print(std)
normalized_arr=(arr10-mean)/std
print(normalized_arr)


5.0
2.581988897471611
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


In [48]:
# Logical Operations

arr11=np.array([1,2,3,4,5,6])
# arr11[(arr11>3)  (arr11<2)]